name: Build AAB

on:
  push:
    branches: [main]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Android App Bundle
    runs-on: ubuntu-latest

    env:
      GROG_API_KEY: ${{ secrets.GROG_API_KEY }}

    steps:
      - run: echo "✅ GitHub Actions работает!"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build AAB
        run: flutter build appbundle --release

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: build/app/outputs/bundle/release/app-release.aab
